[package]
name = "template_rust"
version = "0.1.0"
edition = "2021"

[lib]
path="src/aoc/mod.rs"
name="aoc"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror="1.0.30"
derive_more = "0.99.17"
concat-idents = "1.1.3"